services:
  headscale:
    image: docker.io/headscale/headscale:v0.26.1
    restart: unless-stopped
    container_name: headscale
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ${APP_DATA_DIR}/data/config:/etc/headscale
      - ${APP_DATA_DIR}/data/lib:/var/lib/headscale
      - ${APP_DATA_DIR}/data/run:/var/run/headscale
    command: serve
