services:
  eclipse-mosquitto:
    image: eclipse-mosquitto:2.0.21
    container_name: eclipse-mosquitto
    environment:
      - TZ=${TZ}
    ports:
      - 1883:1883
      - 9001:9001
    command: ['/usr/sbin/mosquitto', '-c', '/mosquitto/config/mosquitto.conf']
    expose:
      - 1883
    volumes:
      - ${APP_DATA_DIR}/data/data:/mosquitto/data
      - ${APP_DATA_DIR}/data/config:/mosquitto/config
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
