services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data:/app/data
    dns:
      - ${DNS_IP}
    ports:
      - ${APP_PORT}:3001
    restart: unless-stopped
    networks:
      - tipi_main_network
