services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1.5.0
    restart: unless-stopped
    environment:
      - "APP_URL": "${POCKET_ID_APP_URL}",
      - "TRUST_PROXY" : "true",
      - "PUID" : "0",
      - "PGID" : "0",
      - "ANALYTICS_DISABLED" : "true"
    ports:
      - ${APP_PORT}:1411
    volumes:
      - "${APP_DATA_DIR}/data:/app/data"
    networks:
      - tipi_main_network
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
