version: '3.7'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.06.2
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
    ports:
      - ${NETWORK_INTERFACE:-0.0.0.0}:53:53/tcp
      - ${NETWORK_INTERFACE:-0.0.0.0}:53:53/udp
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/pihole:/etc/pihole
      - ${APP_DATA_DIR}/data/dnsmasq:/etc/dnsmasq.d
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${APP_PASSWORD}
    cap_add:
      - NET_ADMIN
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
